services:
  sloth:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sloth
    restart: unless-stopped
    environment:
      - HUD_SECRET=bozo
    volumes:
      - ./app:/app
    networks:
      - mainframe-public

networks:
  mainframe-public:
    external: true